### ISSUE TITLE
RuntimeException - Module (Zend\ServiceManagerDi) could not be initialized

### ISSUE THREAD

**Issue by Jayaramki** [jiromm/zf3-skeleton-application#1]
Hi @jiromm ,

I am new to zendframework. I was searched for a complete skeleton application to create a basic MVC structured skeleton-application. Finally I found your repository.  When I tried to run it, I have got the following error message

> Fatal error: Uncaught exception 'Zend\ModuleManager\Exception\RuntimeException' with message 'Module (Zend\ServiceManager\Di) could not be initialized.' in C:\xampp\htdocs\trepr\site_new\vendor\zendframework\zend-modulemanager\src\ModuleManager.php:204 Stack trace: #0 C:\xampp\htdocs\trepr\site_new\vendor\zendframework\zend-modulemanager\src\ModuleManager.php(175): Zend\ModuleManager\ModuleManager->loadModuleByName(Object(Zend\ModuleManager\ModuleEvent)) #1 C:\xampp\htdocs\trepr\site_new\vendor\zendframework\zend-modulemanager\src\ModuleManager.php(97): Zend\ModuleManager\ModuleManager->loadModule('Zend\ServiceMan...') #2 C:\xampp\htdocs\trepr\site_new\vendor\zendframework\zend-eventmanager\src\EventManager.php(271): Zend\ModuleManager\ModuleManager->onLoadModules(Object(Zend\ModuleManager\ModuleEvent)) #3 C:\xampp\htdocs\trepr\site_new\vendor\zendframework\zend-eventmanager\src\EventManager.php(143): Zend\EventManager\EventManager->triggerListeners(Object(Zend\ModuleManager\ModuleEvent)) #4 C:\xampp\htdocs\trepr\site_ne in C:\xampp\htdocs\trepr\site_new\vendor\zendframework\zend-modulemanager\src\ModuleManager.php on line 204

I don't think it is an issue. But may be i missed in any configuration. Can you please guide me where i missed?

**Comment by jiromm** [comment]
Hi @Jayaramki,

It seems you don't have service manager installed, but it was in composer.json as a requirement.
Remove everything and do next actions.

`git clone git@github.com:jiromm/zf3-skeleton-application.git .`
`composer install`

To check that everything works, try

`php -S 0.0.0.0:8080 -t public/ public/index.php`

Then open `http://0.0.0.0:8080/` in browser.

**Comment by jiromm** [comment]
I will update README file.
